services:
  db:
    build:
      context: .
      dockerfile: DB.Dockerfile
    ports:
      - "4306:3306" #docker-compose run --service-ports 명령어 사용해야함.
    networks:
      - stock
  web:
    build:
        context: .
        dockerfile: App.Dockerfile
    command: python3 /home/stock/backend/manage.py runserver
#    depends_on:
#      - db
    ports:
      - "8080:8080"
    networks:
      - stock
networks:
  stock:
    driver: bridge