name: Django CI Test

on:
  push:
    branches: [ "ci-test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: echo test
      run: |
        echo "echo_test" > ../echo.test
        cat ../echo.test

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_HOME_PRIVATE_KEY }}
        port: ${{ secrets.AWS_PORT }}
        # rhel8
        script: |
          pwd
          sudo yum -y update
          sudo yum install -y git
          git --version
          mkdir repository
          cd repository
          git config --global user.name '$GIT_USERNAME'
          git config --global user.password '$GIT_ACCESS_TOKEN'
          git clone https://github.com/lightcat-art/stock-data-analyze.git .
          $GIT_USERNAME
          $GIT_ACCESS_TOKEN
      env:
        GIT_USERNAME: ${{secrets.GIT_USERNAME}}
        GIT_ACCESS_TOKEN: ${{secrets.GIT_ACCESS_TOKEN}}


#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r backend/requirements.txt
#    - name: Run Tests
#      run: |
#        python -V
