name: Django CI Test=='

on:
  push:
    branches: [ "ci-test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Generate SSH Key
      run: |
        # ensure mkdir .ssh folder
        mkdir -p ~/.ssh/
        pwd
        echo "$AWS_HOME_PRIVATE_KEY" > ../private.key
        pwd
        sudo chmod 600 ../private.key
        # echo "$AWS_KNOWN_HOSTS" > ~/.ssh/known_hosts
        cat ../private.key
        cat ~/.ssh/known_hosts
        pwd ~/.ssh/known_hosts
      shell: bash
      env:
        AWS_HOME_PRIVATE_KEY: ${{secrets.AWS_HOME_PRIVATE_KEY}}
        AWS_KNOWN_HOSTS: ${{secrets.AWS_KNOWN_HOSTS}}
        AWS_KEY_PATH: ${{github.workspace}}/../private.key

    - name: SSH Login
      run: |
        pwd
        echo "AWS_KEY_PATH=$AWS_KEY_PATH"
        echo "AWS_IP=$AWS_IP"
        ssh-keygen -R $AWS_IP
        ssh -i $AWS_KEY_PATH $AWS_USER@$AWS_IP
        pwd
        mkdir AWS_LOGIN_SUCCESS
        ls -al
      shell: bash
      env:
        AWS_IP: ${{secrets.AWS_IP}}
        AWS_USER: ${{secrets.AWS_USER}}
        AWS_KEY_PATH: ${{github.workspace}}/../private.key

#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r backend/requirements.txt
#    - name: Run Tests
#      run: |
#        python -V
