name: Django CI Test

on:
  push:
    branches: ["ci-test"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - run: mkdir ~/distfiles
    - uses: actions/download-artifact@v2
      with:
        name: distfiles
        path: distfiles

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: executing remote ssh commands before scp
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CLOUD_IP }}
        username: ${{ secrets.CLOUD_USER }}
#        key: ${{ secrets.AWS_HOME_PRIVATE_KEY }}
        password: ${{ secrets.CLOUD_PASSWD }}
        port: ${{ secrets.CLOUD_PORT }}
        # rhel8
        script: |
          ls -al

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CLOUD_IP }}
        username: ${{ secrets.CLOUD_USER }}
        password: ${{ secrets.CLOUD_PASSWD }}
        port: ${{ secrets.CLOUD_PORT }}
        source: "distfiles/*"
        target: ${{ secrets.TARGET_DIR }}

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CLOUD_IP }}
        username: ${{ secrets.CLOUD_USER }}
#        key: ${{ secrets.AWS_HOME_PRIVATE_KEY }}
        password: ${{ secrets.CLOUD_PASSWD }}
        port: ${{ secrets.CLOUD_PORT }}
        # rhel8
        script: |
          ls -al
#          docker exec -it stock-data-analyze-web /bin/bash
#          ls -al

#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r backend/requirements.txt
#    - name: Run Tests
#      run: |
#        python -V
