# Generated by Django 3.2.15 on 2023-08-16 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('stock_event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUpdateStatus',
            fields=[
                ('stock_info_update_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_type', models.CharField(max_length=1)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('update_type', models.CharField(default='UD', max_length=2)),
                ('mod_dt', models.DateField(default=django.utils.timezone.now)),
                ('reg_dt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('stock_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('open', models.IntegerField(default=-1, null=True)),
                ('close', models.IntegerField(default=-1, null=True)),
                ('high', models.IntegerField(default=-1, null=True)),
                ('low', models.IntegerField(default=-1, null=True)),
                ('volume', models.IntegerField(default=-1, null=True)),
                ('value', models.BigIntegerField(default=-1, null=True)),
                ('up_down_rate', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='종목명을 입력하세요', max_length=200)),
                ('days', models.PositiveIntegerField(help_text='시작날짜로부터 조회할 기간을 선택하세요')),
                ('start_date', models.DateField(help_text='시작날짜를 선택하세요')),
            ],
        ),
        migrations.CreateModel(
            name='SimulResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_simul_param_id', models.IntegerField(default=-1)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('max_rate', models.FloatField(default=0)),
                ('max_days_taken', models.IntegerField(default=0)),
                ('min_rate', models.FloatField(default=0)),
                ('min_days_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='priceinfo',
            index=models.Index(fields=['stock_event_id'], name='stocksimul__stock_e_5b3f74_idx'),
        ),
    ]
