# Generated by Django 3.2.15 on 2022-09-24 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSimulParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('days', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StockSimulResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=200)),
                ('max_rate', models.FloatField(default=0)),
                ('max_days_taken', models.IntegerField(default=0)),
                ('min_rate', models.FloatField(default=0)),
                ('min_days_taken', models.IntegerField(default=0)),
                ('stock_simul_param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksimul.stocksimulparam')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('stock_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.IntegerField(default=-1)),
                ('close', models.IntegerField(default=-1)),
                ('high', models.IntegerField(default=-1)),
                ('low', models.IntegerField(default=-1)),
                ('volume', models.IntegerField(default=-1)),
            ],
            options={
                'index_together': {('event_code', 'date')},
            },
        ),
    ]
