# Generated by Django 3.2.15 on 2022-09-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksimulparam',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
