# Generated by Django 3.2.15 on 2023-11-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalInfo',
            fields=[
                ('fm_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(null=True)),
                ('quarter', models.CharField(max_length=6, null=True)),
                ('stock_tot_co', models.BigIntegerField(null=True)),
                ('cap', models.BigIntegerField(null=True)),
                ('eps', models.IntegerField(null=True)),
                ('bps', models.IntegerField(blank=True, null=True)),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('roe', models.FloatField(null=True)),
                ('profit_loss', models.BigIntegerField(null=True)),
                ('profit_loss_control', models.BigIntegerField(null=True)),
                ('profit_loss_non_control', models.BigIntegerField(null=True)),
                ('profit_loss_before_tax', models.BigIntegerField(null=True)),
                ('assets', models.BigIntegerField(null=True)),
                ('current_assets', models.BigIntegerField(null=True)),
                ('non_current_assets', models.BigIntegerField(null=True)),
                ('liabilities', models.BigIntegerField(null=True)),
                ('current_liabilities', models.BigIntegerField(null=True)),
                ('non_current_liabilities', models.BigIntegerField(null=True)),
                ('equity', models.BigIntegerField(null=True)),
                ('equity_control', models.BigIntegerField(null=True)),
                ('equity_non_control', models.BigIntegerField(null=True)),
                ('revenue', models.BigIntegerField(null=True)),
                ('cost_of_sales', models.BigIntegerField(null=True)),
                ('gross_profit', models.BigIntegerField(null=True)),
                ('operating_income_loss', models.BigIntegerField(null=True)),
                ('investing_cash_flow', models.BigIntegerField(null=True)),
                ('operating_cash_flow', models.BigIntegerField(null=True)),
                ('financing_cash_flow', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotAdjPriceInfo',
            fields=[
                ('not_adj_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('open', models.IntegerField(null=True)),
                ('close', models.IntegerField(null=True)),
                ('high', models.IntegerField(null=True)),
                ('low', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('value', models.BigIntegerField(null=True)),
                ('up_down_rate', models.FloatField(null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('listed_shares', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='priceinfo',
            name='stocksimul__stock_e_5b3f74_idx',
        ),
        migrations.AlterField(
            model_name='infoupdatestatus',
            name='mod_dt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='infoupdatestatus',
            name='stock_event_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='infoupdatestatus',
            name='update_type',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='close',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='low',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='open',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='stock_event_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='up_down_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='priceinfo',
            index=models.Index(fields=['stock_event_id'], name='idx_priceinfo_1'),
        ),
        migrations.AddIndex(
            model_name='notadjpriceinfo',
            index=models.Index(fields=['stock_event_id'], name='idx_notadj_priceinfo_1'),
        ),
        migrations.AddIndex(
            model_name='notadjpriceinfo',
            index=models.Index(fields=['stock_event_id', 'date'], name='idx_notadj_priceinfo_2'),
        ),
        migrations.AddIndex(
            model_name='fundamentalinfo',
            index=models.Index(fields=['stock_event_id'], name='idx_fundinfo_1'),
        ),
        migrations.AddIndex(
            model_name='fundamentalinfo',
            index=models.Index(fields=['stock_event_id', 'quarter'], name='idx_fundinfo_2'),
        ),
    ]
