# Generated by Django 3.2.15 on 2023-12-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIndicator',
            fields=[
                ('fi_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('bps', models.FloatField(null=True)),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('eps', models.IntegerField(null=True)),
                ('div', models.FloatField(null=True)),
                ('dps', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotAdjPriceInfo',
            fields=[
                ('not_adj_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('open', models.IntegerField(null=True)),
                ('close', models.IntegerField(null=True)),
                ('high', models.IntegerField(null=True)),
                ('low', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('value', models.BigIntegerField(null=True)),
                ('up_down_rate', models.FloatField(null=True)),
                ('up_down_sort', models.CharField(max_length=2, null=True)),
                ('up_down_value', models.IntegerField(null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('listed_shares', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='priceinfo',
            name='stocksimul__stock_e_5b3f74_idx',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='mkt_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='infoupdatestatus',
            name='mod_dt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='infoupdatestatus',
            name='update_type',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='close',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='low',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='open',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='up_down_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='priceinfo',
            index=models.Index(fields=['stock_event_id'], name='idx_priceinfo_1'),
        ),
        migrations.AddIndex(
            model_name='notadjpriceinfo',
            index=models.Index(fields=['stock_event_id'], name='idx_notadj_priceinfo_1'),
        ),
        migrations.AddIndex(
            model_name='notadjpriceinfo',
            index=models.Index(fields=['stock_event_id', 'date'], name='idx_notadj_priceinfo_2'),
        ),
        migrations.AddIndex(
            model_name='financialindicator',
            index=models.Index(fields=['stock_event_id'], name='idx_fin_indic_1'),
        ),
        migrations.AddIndex(
            model_name='financialindicator',
            index=models.Index(fields=['stock_event_id', 'date'], name='idx_fin_indic_2'),
        ),
    ]
