# Generated by Django 3.2.15 on 2022-09-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfoupdatestatus',
            name='detail_info_1',
        ),
        migrations.RemoveField(
            model_name='stockinfoupdatestatus',
            name='detail_info_2',
        ),
        migrations.AddField(
            model_name='stockinfoupdatestatus',
            name='stock_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocksimul.stockevent'),
        ),
    ]
