# Generated by Django 3.2.15 on 2023-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalInfo',
            fields=[
                ('fm_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('quarter', models.CharField(max_length=6)),
                ('stock_tot_co', models.BigIntegerField(default=0)),
                ('cap', models.BigIntegerField(default=0)),
                ('eps', models.IntegerField(default=0)),
                ('bps', models.IntegerField(default=0)),
                ('per', models.FloatField(default=0)),
                ('pbr', models.FloatField(default=0)),
                ('roe', models.FloatField(default=0)),
                ('profit_loss', models.BigIntegerField(default=0)),
                ('profit_loss_control', models.BigIntegerField(default=0)),
                ('profit_loss_non_control', models.BigIntegerField(default=0)),
                ('profit_loss_before_tax', models.BigIntegerField(default=0)),
                ('assets', models.BigIntegerField(default=0)),
                ('liabilities', models.BigIntegerField(default=0)),
                ('equity', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('operating_income_loss', models.BigIntegerField(default=0)),
                ('investing_cash_flow', models.BigIntegerField(default=0)),
                ('operating_cash_flow', models.BigIntegerField(default=0)),
                ('financing_cash_flow', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotAdjPriceInfo',
            fields=[
                ('not_adj_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('open', models.IntegerField(default=-1, null=True)),
                ('close', models.IntegerField(default=-1, null=True)),
                ('high', models.IntegerField(default=-1, null=True)),
                ('low', models.IntegerField(default=-1, null=True)),
                ('volume', models.IntegerField(default=-1, null=True)),
                ('value', models.BigIntegerField(default=-1, null=True)),
                ('up_down_rate', models.FloatField(default=0, null=True)),
                ('market_cap', models.BigIntegerField(default=-1, null=True)),
                ('listed_shares', models.BigIntegerField(default=-1, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='notadjpriceinfo',
            index=models.Index(fields=['stock_event_id'], name='stocksimul__stock_e_82ce35_idx'),
        ),
    ]
