# Generated by Django 3.2.15 on 2023-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0002_fundamentalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotAdjPriceInfo',
            fields=[
                ('not_adj_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('open', models.IntegerField(default=-1, null=True)),
                ('close', models.IntegerField(default=-1, null=True)),
                ('high', models.IntegerField(default=-1, null=True)),
                ('low', models.IntegerField(default=-1, null=True)),
                ('volume', models.IntegerField(default=-1, null=True)),
                ('value', models.BigIntegerField(default=-1, null=True)),
                ('up_down_rate', models.FloatField(default=0, null=True)),
                ('market_cap', models.BigIntegerField(default=-1, null=True)),
                ('listed_shares', models.BigIntegerField(default=-1, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='notadjpriceinfo',
            index=models.Index(fields=['stock_event_id'], name='stocksimul__stock_e_82ce35_idx'),
        ),
    ]
