# Generated by Django 3.2.15 on 2022-09-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0002_stocksimulparam_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSimulResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=200)),
                ('max_rate', models.FloatField(default=0)),
                ('max_days_taken', models.IntegerField(default=0)),
                ('min_rate', models.FloatField(default=0)),
                ('min_days_taken', models.IntegerField(default=0)),
                ('stock_simul_param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksimul.stocksimulparam')),
            ],
        ),
    ]
