# Generated by Django 3.2.15 on 2023-11-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0002_auto_20231128_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='assets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='cost_of_sales',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='current_assets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='current_liabilities',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='equity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='equity_control',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='equity_non_control',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='financing_cash_flow',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='gross_profit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='investing_cash_flow',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='liabilities',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='non_current_assets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='non_current_liabilities',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='operating_cash_flow',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='operating_income_loss',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='profit_loss',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='profit_loss_before_tax',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='profit_loss_control',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='profit_loss_non_control',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='revenue',
            field=models.BigIntegerField(default=0),
        ),
    ]
