# Generated by Django 3.2.15 on 2022-09-29 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0002_auto_20220926_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksimulparam',
            name='days',
            field=models.PositiveIntegerField(default=1, help_text='시작날짜로부터 조회할 기간을 선택하세요'),
        ),
        migrations.AlterField(
            model_name='stocksimulparam',
            name='event_name',
            field=models.CharField(help_text='종목명을 입력하세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='stocksimulparam',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='시작날짜를 선택하세요'),
        ),
    ]
