# Generated by Django 3.2.15 on 2023-12-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0002_auto_20231208_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='mkt_status',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
