# Generated by Django 3.2.15 on 2022-09-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0003_stocksimulresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('event_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start', models.IntegerField(default=-1)),
                ('end', models.IntegerField(default=-1)),
                ('high', models.IntegerField(default=-1)),
                ('row', models.IntegerField(default=-1)),
                ('volume', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('event_code', 'date'), name='unique_event_code_date'),
        ),
    ]
