# Generated by Django 3.2.15 on 2023-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0003_eventinfo_mkt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignHoldingVol',
            fields=[
                ('fh_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('hold_quantity', models.BigIntegerField(null=True)),
                ('sharehold_rate', models.FloatField(null=True)),
                ('limit_quantity', models.BigIntegerField(null=True)),
                ('limit_exhaustion_rate', models.FloatField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='foreignholdingvol',
            index=models.Index(fields=['stock_event_id'], name='idx_fh_indic_1'),
        ),
        migrations.AddIndex(
            model_name='foreignholdingvol',
            index=models.Index(fields=['stock_event_id', 'date'], name='idx_fh_indic_2'),
        ),
    ]
