# Generated by Django 3.2.15 on 2022-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0003_auto_20220929_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='up_down_rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='value',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='stocksimulparam',
            name='days',
            field=models.PositiveIntegerField(help_text='시작날짜로부터 조회할 기간을 선택하세요'),
        ),
        migrations.AlterField(
            model_name='stocksimulparam',
            name='start_date',
            field=models.DateField(help_text='시작날짜를 선택하세요'),
        ),
    ]
