# Generated by Django 3.2.15 on 2023-12-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0003_eventinfo_mkt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignHoldingVol',
            fields=[
                ('fh_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('hold_quantity', models.BigIntegerField(null=True)),
                ('sharehold_rate', models.FloatField(null=True)),
                ('limit_quantity', models.BigIntegerField(null=True)),
                ('limit_exhaustion_rate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexBasicInfo',
            fields=[
                ('stock_index_id', models.AutoField(primary_key=True, serialize=False)),
                ('index_code', models.CharField(default=-1, max_length=10)),
                ('index_nm', models.CharField(max_length=100)),
                ('mkt_code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexContainMapInfo',
            fields=[
                ('iem_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_index_id', models.IntegerField(default=-1)),
                ('event_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPriceInfo',
            fields=[
                ('ip_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_index_id', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('open', models.IntegerField(null=True)),
                ('close', models.IntegerField(null=True)),
                ('high', models.IntegerField(null=True)),
                ('low', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('value', models.BigIntegerField(null=True)),
                ('up_down_rate', models.FloatField(null=True)),
                ('up_down_sort', models.CharField(max_length=2, null=True)),
                ('up_down_value', models.IntegerField(null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='infoupdatestatus',
            old_name='stock_event_id',
            new_name='class_id',
        ),
        migrations.AlterField(
            model_name='infoupdatestatus',
            name='table_type',
            field=models.CharField(max_length=2),
        ),
        migrations.AddIndex(
            model_name='infoupdatestatus',
            index=models.Index(fields=['table_type', 'class_id'], name='idx_update_status_1'),
        ),
        migrations.AddIndex(
            model_name='indexpriceinfo',
            index=models.Index(fields=['stock_index_id'], name='idx_ip_info_1'),
        ),
        migrations.AddIndex(
            model_name='indexcontainmapinfo',
            index=models.Index(fields=['stock_index_id'], name='idx_iem_info_1'),
        ),
        migrations.AddIndex(
            model_name='indexcontainmapinfo',
            index=models.Index(fields=['event_code'], name='idx_iem_info_2'),
        ),
        migrations.AddIndex(
            model_name='indexbasicinfo',
            index=models.Index(fields=['index_code'], name='idx_ib_info_1'),
        ),
        migrations.AddIndex(
            model_name='indexbasicinfo',
            index=models.Index(fields=['index_nm'], name='idx_ib_info_2'),
        ),
        migrations.AddIndex(
            model_name='indexbasicinfo',
            index=models.Index(fields=['mkt_code'], name='idx_ib_info_3'),
        ),
        migrations.AddIndex(
            model_name='foreignholdingvol',
            index=models.Index(fields=['stock_event_id'], name='idx_fh_indic_1'),
        ),
        migrations.AddIndex(
            model_name='foreignholdingvol',
            index=models.Index(fields=['stock_event_id', 'date'], name='idx_fh_indic_2'),
        ),
    ]
