# Generated by Django 3.2.15 on 2023-12-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0004_auto_20231217_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpriceinfo',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indexpriceinfo',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indexpriceinfo',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indexpriceinfo',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indexpriceinfo',
            name='up_down_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='indexpriceinfo',
            index=models.Index(fields=['stock_index_id', 'date'], name='idx_ip_info_2'),
        ),
    ]
