# Generated by Django 3.2.15 on 2022-10-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0004_auto_20221002_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfoupdatestatus',
            name='update_type',
            field=models.CharField(default='UP', max_length=2),
        ),
    ]
