# Generated by Django 3.2.15 on 2023-11-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0004_alter_fundamentalinfo_profit_loss_non_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentalinfo',
            name='profit_loss_non_control',
            field=models.BigIntegerField(default=0),
        ),
    ]
