# Generated by Django 3.2.15 on 2022-09-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0004_auto_20220925_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprice',
            old_name='start',
            new_name='open',
        ),
    ]
