# Generated by Django 3.2.15 on 2023-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0004_auto_20231217_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbasicinfo',
            name='index_dense_nm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indexbasicinfo',
            name='index_nm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='indexbasicinfo',
            index=models.Index(fields=['index_dense_nm'], name='idx_ib_info_4'),
        ),
    ]
