# Generated by Django 3.2.15 on 2023-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0005_alter_fundamentalinfo_profit_loss_non_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='mkt_nm',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='notadjpriceinfo',
            name='up_down_sort',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='notadjpriceinfo',
            name='up_down_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='listed_shares',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='up_down_sort',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='up_down_value',
            field=models.IntegerField(null=True),
        ),
    ]
