# Generated by Django 3.2.15 on 2022-10-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0005_stockinfoupdatestatus_update_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfoupdatestatus',
            name='update_type',
            field=models.CharField(default='UD', max_length=2),
        ),
    ]
