# Generated by Django 3.2.15 on 2022-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0006_alter_stockinfoupdatestatus_update_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='value',
            field=models.BigIntegerField(default=-1, null=True),
        ),
    ]
