# Generated by Django 3.2.15 on 2023-12-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0006_auto_20231203_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
