# Generated by Django 3.2.15 on 2023-06-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0007_alter_stockprice_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfoupdatestatus',
            name='stock_event',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='stock_event',
        ),
        migrations.RemoveField(
            model_name='stocksimulresult',
            name='stock_event',
        ),
        migrations.RemoveField(
            model_name='stocksimulresult',
            name='stock_simul_param',
        ),
        migrations.AddField(
            model_name='stockinfoupdatestatus',
            name='stock_event_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='stock_event_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stocksimulresult',
            name='stock_event_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stocksimulresult',
            name='stock_simul_param_id',
            field=models.IntegerField(default=-1),
        ),
    ]
