# Generated by Django 3.2.15 on 2023-12-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0007_alter_eventinfo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinfo',
            name='listed_shares',
        ),
        migrations.RemoveField(
            model_name='priceinfo',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='priceinfo',
            name='up_down_sort',
        ),
        migrations.RemoveField(
            model_name='priceinfo',
            name='up_down_value',
        ),
    ]
