# Generated by Django 3.2.15 on 2023-12-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0008_auto_20231203_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentalinfo',
            name='stock_normal_co',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fundamentalinfo',
            name='stock_prior_co',
            field=models.BigIntegerField(null=True),
        ),
    ]
