# Generated by Django 3.2.15 on 2023-12-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0009_auto_20231204_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('fs_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(null=True)),
                ('quarter', models.CharField(max_length=6, null=True)),
                ('eps', models.IntegerField(null=True)),
                ('profit_loss', models.BigIntegerField(default=0)),
                ('profit_loss_control', models.BigIntegerField(default=0)),
                ('profit_loss_non_control', models.BigIntegerField(default=0)),
                ('profit_loss_before_tax', models.BigIntegerField(default=0)),
                ('assets', models.BigIntegerField(default=0)),
                ('current_assets', models.BigIntegerField(default=0)),
                ('non_current_assets', models.BigIntegerField(default=0)),
                ('liabilities', models.BigIntegerField(default=0)),
                ('current_liabilities', models.BigIntegerField(default=0)),
                ('non_current_liabilities', models.BigIntegerField(default=0)),
                ('equity', models.BigIntegerField(default=0)),
                ('equity_control', models.BigIntegerField(default=0)),
                ('equity_non_control', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('cost_of_sales', models.BigIntegerField(default=0)),
                ('gross_profit', models.BigIntegerField(default=0)),
                ('operating_income_loss', models.BigIntegerField(default=0)),
                ('investing_cash_flow', models.BigIntegerField(default=0)),
                ('operating_cash_flow', models.BigIntegerField(default=0)),
                ('financing_cash_flow', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockShares',
            fields=[
                ('shares_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(null=True)),
                ('quarter', models.CharField(max_length=6, null=True)),
                ('stock_tot_co', models.BigIntegerField(null=True)),
                ('stock_normal_co', models.BigIntegerField(null=True)),
                ('stock_prior_co', models.BigIntegerField(null=True)),
                ('distb_stock_tot_co', models.BigIntegerField(null=True)),
                ('distb_stock_normal_co', models.BigIntegerField(null=True)),
                ('distb_stock_prior_co', models.BigIntegerField(null=True)),
                ('tes_stock_tot_co', models.BigIntegerField(null=True)),
                ('tes_stock_normal_co', models.BigIntegerField(null=True)),
                ('tes_stock_prior_co', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FundamentalInfo',
        ),
        migrations.AddIndex(
            model_name='stockshares',
            index=models.Index(fields=['stock_event_id'], name='idx_shares_1'),
        ),
        migrations.AddIndex(
            model_name='stockshares',
            index=models.Index(fields=['stock_event_id', 'quarter'], name='idx_shares_2'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['stock_event_id'], name='idx_fundinfo_1'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['stock_event_id', 'quarter'], name='idx_fundinfo_2'),
        ),
    ]
