# Generated by Django 3.2.15 on 2023-12-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0010_auto_20231205_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementSkip',
            fields=[
                ('fss_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(null=True)),
                ('quarter', models.CharField(max_length=6, null=True)),
                ('skip_yn', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
