# Generated by Django 3.2.15 on 2023-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0011_financialstatementskip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIndicator',
            fields=[
                ('fi_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_event_id', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('bps', models.FloatField(null=True)),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('eps', models.IntegerField(null=True)),
                ('div', models.FloatField(null=True)),
                ('dps', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='financialindicator',
            index=models.Index(fields=['stock_event_id'], name='idx_fin_indic_1'),
        ),
        migrations.AddIndex(
            model_name='financialindicator',
            index=models.Index(fields=['stock_event_id', 'date'], name='idx_fin_indic_2'),
        ),
    ]
