# Generated by Django 3.2.15 on 2023-12-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksimul', '0012_auto_20231205_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinfo',
            old_name='mkt_nm',
            new_name='mkt_code',
        ),
    ]
